### ISSUE TITLE
TODO: SCHOOLS - Data Cleansing

### ISSUE THREAD

**Issue by itisaasta** [ashwindeo/dataschoolers#1]
Do any data cleansing necessary for the SCHOOLS dataset.

**Comment by ashwindeo** [comment]
Ack. Looking into

**Comment by ashwindeo** [comment]
Renamed and dropped columns from schools.csv
Updated schools demographic data is stored in schools_v1.csv
Column information is stored under schools_rc.csv
All these files are under "File Store" directory

**Comment by ashwindeo** [comment]
●      Key for missing/NA/etc:
○      † indicates that the data are not applicable.
○      – indicates that the data are missing.
○      ‡ indicates that the data do not meet NCES data quality standards.

Will have to decide if we want to replace these with something else. Overall data quality looks good.

**Comment by kannab** [comment]
I guess these spl. characters will cause issues somewhere down the line (visualization etc.). I think it's best to replace them with some code. May be something like below:

Replace † with NA indicating Not Application
Replace – with ND indicating No Idea
Replace ‡ with NQ indicating No Quality

Let me know where is the clean dataset so that I can start EDA

**Comment by ashwindeo** [comment]
As per http://pandas.pydata.org/pandas-docs/stable/missing_data.html, it is best to replace missing / bad data with NaNs.

Kindly take a look at : data_cleanup_school.ipynb
1) Contains the notations used for formulating the column names.
2) Goes over the various steps taken to cleanup / reformat the data. They include :
a) Replacing missing/ bad data with NaNs
b) Getting rid of unnecessary double quotes, especially around numbers
c) Converting about 20 columns that to boolean True/False
d) Converting about 290 columns to floats. They mainly were storing school demographics.

The cleaned up file is stored as schools_v2.csv in the "File Store" directory on our Google Drive shared folder. The size of this file is about half of the original.

Kindly eyeball the csv, so check if any additional work is needed in terms on cleanup.
Thanks.

**Comment by kannab** [comment]
Ashwin - Reviewed the csv file and everything seems to be OK. Brendan could use same logic to clean-up districts.csv. This will be keep the column names consistent between two CSVs.

**Comment by kannab** [comment]
Ashwin - you renamed ungraded students to gug not ug as indicated in your table. Not a big deal but just wanted to let you know :)

**Comment by ashwindeo** [comment]
It was "Grade - Ungraded" so was not sure how to label it.. so used g + ug :)

**Comment by ashwindeo** [comment]
Closing this issue now. Feel free to reopen it, if any additional work is needed.
