### ISSUE TITLE
TODO: DISTRICTS - Model 1 - Decision Tree

### ISSUE THREAD

**Issue by itisaasta** [ashwindeo/dataschoolers#10]

**Comment by ashwindeo** [comment]
Looking into.

**Comment by ashwindeo** [comment]
This is done in 
https://github.com/ashwindeo/dataschoolers/blob/master/Classifier_Ensemble_Methods.ipynb

For school districts data set :
1) Indicators used : Funding/Expenditure/Location/School and Race/Sex
Accuracy on training data: 0.80
Accuracy on test data:     0.75

2) Indicators used : Funding/Expenditure/Location/School Types. No Race or Sex : 
Accuracy on training data: 0.78
Accuracy on test data:     0.76
