### ISSUE TITLE
TODO: SCHOOLS - Exploratory Data Analysis

### ISSUE THREAD

**Issue by itisaasta** [ashwindeo/dataschoolers#2]
Perform exploratory data analysis for the schools dataset.  Understand what columns are available to us and group them accordingly.

**Comment by kannab** [comment]
Folks - What do you think is the Response column in schools.csv? I cannot identify one? Please help!

**Comment by ashwindeo** [comment]
Yeah, even I am not sure about that. From what I saw, this dataset essentially contains all the demographic information at per school level. We could use this data to 'complement' other data set that contains some key metrics/response columns like test scores, graduation rates etc.
Compared to this, the district level data which Brendan cleaned out looks more promising.

**Comment by itisaasta** [comment]
Thinking we build the models on the district level data.  When we find factors of interest, we can provide more thorough explanations using the school level data if needed.

**Comment by ashwindeo** [comment]
I agree, we can use this school level data more for case studies and visualization purpose.
It also has lat/longitude information which we can use to overlay on the map. Can show nice spreads for different factors like diverity, student/teacher ratio, test scores(sourced from district level), funding etc.
